# Generated by Django 5.2.8 on 2025-11-24 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_categoria_options_alter_vehiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='blog.categoria'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(help_text='Ej: Auto, Moto, SUV, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/fotos/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='blog.vehiculo')),
            ],
        ),
    ]
