# Generated by Django 5.2.8 on 2025-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_categoria_options_alter_vehiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Ejemplo: 1250000.00', max_digits=12),
            preserve_default=False,
        ),
    ]
